name: Verify IDE compatibility
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - plugin/ide
  pull_request:
    paths:
      - plugin/ide

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Run Verify Plugin task and IntelliJ Plugin Verifier tool
      - name: Run Plugin Verification tasks
        run: ./gradlew runPluginVerifier